# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a646987ad16ab8b226ea2266cfb83be402af051fa53069bb95cc1c95f0b64c321cb0bf3651996cf8b57af51c4430156496ab5f56eeb434929e868bf921ce687

test:
  secret_key_base: f17009f1525669633cd8a3080ef45afef6e6c7762a2389e05b5e24df7a4820a47acfd03e0e20a3c74b9ac1166db572288e196612c6c66f2bf3e3c6e647268105

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
